name: Minecraft Server Tests
on: [push]

jobs:
  minecraft-server-test:
    runs-on: ubuntu-latest
    container: node:18-alpine

    services:
      mcserver:
        image: itzg/minecraft-server
        env: 
          EULA: TRUE
          ONLINE_MODE: FALSE
          MOTD: "Minecraft Server Tests"
          MAX_PLAYERS: 1
          TYPE: PAPER
          VERSION: 1.18
        options: -v ${{ github.workspace }}/data-mc-server:/data --name mc-server


    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Restart Server
        uses: docker://docker
        with:
          args: docker restart mc-server

      - name: Install Dependencies
        run: | 
          cd mc-client-bot-tests 
          yarn

      - name: Run Tests
        run: | 
          cd mc-client-bot-tests
          yarn run test
        env:
          HOST: mc-server
          PORT: 25565



