name: Minecraft Server Tests
on: [push]

jobs:
  minecraft-server-test:
    runs-on: ubuntu-latest
    container: node:18-alpine

    services:
      mcserver:
        image: itzg/minecraft-server
        env: 
          EULA: TRUE
          ONLINE_MODE: FALSE
          MOTD: "Minecraft Server Tests"
          MAX_PLAYERS: 1
          TYPE: PAPER
          VERSION: 1.18
        options: --name mcserver
        volumes:
          - data-mc-server:/data


    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Check Docker
        uses: docker://docker
        with: 
          args: docker exec mcserver cat .data/server.properties

      - name: Install Dependencies
        run: | 
          cd mc-client-bot-tests 
          yarn

      - name: Run Tests
        run: | 
          cd mc-client-bot-tests
          yarn run test
        env:
          HOST: mcserver
          PORT: 25565



